<a href="https://colab.research.google.com/github/Qaiserfarooq285/Labtasks/blob/main/Lab5task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import random

# Function to create a 8 queens board
def create_8_queens_board():
    queens_board = np.full((8, 8), '.')
    for row in range(8):
        col = random.randint(0, 7)
        queens_board[row, col] = 'Q'
    return queens_board

# Function to extract chromosome representation of a board (queen positions in each row)
def board_chromosome(board):
    queens_positions = np.argwhere(board == 'Q')
    print(queens_positions)
    cols = queens_positions[:, 1]
    return cols

# Function to calculate fitness based on non-attacking pairs of queens
def calculate_fitness_numpy(board):
    queens_positions = np.argwhere(board == 'Q')
    num_queens = len(queens_positions)
    rows = queens_positions[:, 0]
    cols = queens_positions[:, 1]
    col_attacks = num_queens - len(np.unique(cols))
    main_diagonal_attacks = num_queens - len(np.unique(rows - cols))
    anti_diagonal_attacks = num_queens - len(np.unique(rows + cols))
    total_attacks = col_attacks + main_diagonal_attacks + anti_diagonal_attacks
    fitness = num_queens - total_attacks
    return fitness

# Function to select top two chromosomes based on fitness
def top_two_chromosomes(boards, chromosomes, fitness_values):
    combined = list(zip(fitness_values, boards, chromosomes))
    sorted_combined = sorted(combined, key=lambda x: x[0])
    top_two = sorted_combined[-2:]
    return top_two

# Function to perform single-point crossover between two parents
def single_point_crossover(parent1, parent2):
    # crossover_point = np.random.randint(1, len(parent1) - 1)
    crossover_point = 4
    offspring1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    offspring2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
    return offspring1, offspring2

# Function to perform mutation on a chromosome by randomly altering a gene
def mutate_chromosome(chromosome):
    mutation_index = random.randint(0, 7) #to select random number eg if 3 it means we are selecting queen at row 3 in chromosome
    new_value = random.randint(0, 7)     #this will select random number and that will be the new column for selected queen
    chromosome[mutation_index] = new_value
    return chromosome

# Function to initialize a population of boards
def initialize_population(pop_size):
    population = []
    for _ in range(pop_size):
        board = create_8_queens_board()
        chromosome = board_chromosome(board)
        fitness = calculate_fitness_numpy(board)
        population.append((fitness, board, chromosome))
    return population

# Main function to execute the genetic algorithm for a single selection, crossover, mutation, and fitness evaluation round
def genetic_algorithm(pop_size):
    population = initialize_population(pop_size)

    # Print the initial population
    print("********* Initial Population *********")
    for fitness, board, chromosome in population:
        print(board)
        print("Chromosome:", chromosome)
        print("Fitness:", fitness)
        print("-----------------")

    # Sort and select top two chromosomes
    population = sorted(population, key=lambda x: x[0])
    top_two = population[-2:]
    parent1 = top_two[-1][2]
    parent2 = top_two[-2][2]

    print("********* Selection *********")
    print("Parent 1 Chromosome:", parent1)
    print("Parent 2 Chromosome:", parent2)

    # Perform crossover to generate offspring
    print("********* Crossover *********")
    offspring1, offspring2 = single_point_crossover(parent1, parent2)
    print("Crossover Point Offspring 1:", offspring1)
    print("Crossover Point Offspring 2:", offspring2)

    # Mutate the offspring
    print("********* Mutation *********")
    offspring1 = mutate_chromosome(offspring1)
    offspring2 = mutate_chromosome(offspring2)
    print("After Mutation Offspring 1:", offspring1)
    print("After Mutation Offspring 2:", offspring2)

    # Create new boards based on mutated offspring and calculate fitness
    offspring1_board = np.full((8, 8), '.')
    offspring2_board = np.full((8, 8), '.')
    for row, col in enumerate(offspring1):
        offspring1_board[row, col] = 'Q'
    for row, col in enumerate(offspring2):
        offspring2_board[row, col] = 'Q'

    # Calculate fitness for offspring
    fitness_offspring1 = calculate_fitness_numpy(offspring1_board)
    fitness_offspring2 = calculate_fitness_numpy(offspring2_board)

    # Display the results of offspring
    print("********* Offspring Fitness and Boards *********")
    print("Offspring 1 Board:")
    print(offspring1_board)
    print("Chromosome:", offspring1)
    print("Fitness:", fitness_offspring1)
    print("-----------------")
    print("Offspring 2 Board:")
    print(offspring2_board)
    print("Chromosome:", offspring2)
    print("Fitness:", fitness_offspring2)

# Get user input for population size
pop_size = int(input("Enter the population size: "))
genetic_algorithm(pop_size)


Enter the population size: 4
[[0 4]
 [1 4]
 [2 6]
 [3 2]
 [4 0]
 [5 5]
 [6 7]
 [7 5]]
[[0 0]
 [1 0]
 [2 3]
 [3 2]
 [4 4]
 [5 1]
 [6 0]
 [7 7]]
[[0 3]
 [1 3]
 [2 3]
 [3 0]
 [4 7]
 [5 3]
 [6 3]
 [7 2]]
[[0 2]
 [1 2]
 [2 3]
 [3 6]
 [4 3]
 [5 2]
 [6 6]
 [7 1]]
********* Initial Population *********
[['.' '.' '.' '.' 'Q' '.' '.' '.']
 ['.' '.' '.' '.' 'Q' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' 'Q' '.']
 ['.' '.' 'Q' '.' '.' '.' '.' '.']
 ['Q' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' 'Q' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' 'Q']
 ['.' '.' '.' '.' '.' 'Q' '.' '.']]
Chromosome: [4 4 6 2 0 5 7 5]
Fitness: 3
-----------------
[['Q' '.' '.' '.' '.' '.' '.' '.']
 ['Q' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' 'Q' '.' '.' '.' '.']
 ['.' '.' 'Q' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' 'Q' '.' '.' '.']
 ['.' 'Q' '.' '.' '.' '.' '.' '.']
 ['Q' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' 'Q']]
Chromosome: [0 0 3 2 4 1 0 7]
Fitness: 1
-----------------
[['.' '.' '.' 'Q' '.' '.